const Orange = require('orange-bot')
const DiscordJS = require('discord.js')
const client = new DiscordJS.Client()
const orange = new Orange(client)
const logger = new orange.Logger("yes")
logger.log("&aSuccessfully connected to &bMySQL&a!")
logger.warn("&aSuccessfully connected to &bMySQL&a!")
logger.error("&aSuccessfully connected to &bMySQL&a!")