const Orange = require('orange-bot')()
const logger = new Orange.Logger()
logger.log("&aSuccessfully connected to &bMySQL&a!")
logger.warn("&aSuccessfully connected to &bMySQL&a!")
logger.error("&aSuccessfully connected to &bMySQL&a!")